version: '3'
services:
  eclipse-mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "/mosquitto/data"
      - "/mosquitto/log"
      - "conf/mosquitto.conf:/mosquitto/config/mosquitto.conf"
  hana-injector:
    build: ../
    ports:
      - "8080:8080"
    environment:
      HANA_INJECTOR_CONFIG_FILE_PATH: /storage/conf/config.yml
    volumes:
      - "/storage:/storage"
      - "./config/config.yml:/storage/conf/config.yml"