name: PR checks

on:
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'

      - name: Install the requirements
        run: pip install -r requirements.txt && pip install pytest

      - name: Replace the configuration
        run: |
          sed -i "s|template: injector/templates|template: $PWD/injector/templates|g" ./test/unittests/config/config.yml

      - name: Execute the unittests
        run: export PYTHONPATH=$PYTHONPATH:$PWD/injector && cd test/unittests && export HANA_INJECTOR_CONFIG_FILE_PATH=$PWD/config/config.yml && pytest

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'

      - name: Install the requirements
        run: pip install -r requirements.txt

      - name: Execute the linting checks
        uses: reviewdog/action-flake8@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          flake8_args: --config=.flake8

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'

      - name: Install the requirements
        run: pip install -r requirements.txt && pip install pytest pytest-cov coverage-badge pydoc-markdown==4.6.3 mkdocs mkdocs-material

      - name: Replace the configuration
        run: |
          sed -i "s|template: injector/templates|template: $PWD/injector/templates|g" ./test/unittests/config/config.yml

      - name: Generate the coverage report
        run: export PYTHONPATH=$PYTHONPATH:$PWD/injector && cd test/unittests && export HANA_INJECTOR_CONFIG_FILE_PATH=$PWD/config/config.yml && pytest --junitxml=pytest.xml --cov=. | tee pytest-coverage.txt

      - name: Execute the coverage checks
        uses: MishaKav/pytest-coverage-comment@v1.1.49
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pytest-coverage-path: ./test/unittests/pytest-coverage.txt
          junitxml-path: ./test/unittests/pytest.xml
          hide-badge: true
          create-new-commit: true

      - name: Generate coverage badge
        run: cd test/unittests && coverage-badge -f -o ../../docs/coverage.svg

      - name: Check changed files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: |
            docs

      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --force docs
          git commit -m "docs: Add coverage badge"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          atomic: false

  documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'

      - name: Install the requirements
        run: pip install pydoc-markdown==4.6.3 mkdocs mkdocs-material

      - name: Generate documentation
        run: pydoc-markdown --render-toc && rm -rf docs/content && mv build/docs/* docs

      - name: Check changed files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: |
            docs

      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --force docs
          git commit -m "docs: Add the documentation"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
